// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourist_Agency_MVC.Data;

namespace Tourist_Agency_MVC.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Activities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Available_Season")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Special_Need")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agency_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agency_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agency_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agency_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agency_Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agency");
                });

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Of_Booking")
                        .HasColumnType("datetime2");

                    b.Property<int>("Package_Id")
                        .HasColumnType("int");

                    b.Property<int?>("packageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("packageId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Packages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("Activity_Id")
                        .HasColumnType("int");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<int>("Agency_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Package_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AgencyId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Booking", b =>
                {
                    b.HasOne("Tourist_Agency_MVC.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Tourist_Agency_MVC.Models.Packages", "package")
                        .WithMany()
                        .HasForeignKey("packageId");

                    b.Navigation("Customer");

                    b.Navigation("package");
                });

            modelBuilder.Entity("Tourist_Agency_MVC.Models.Packages", b =>
                {
                    b.HasOne("Tourist_Agency_MVC.Models.Activities", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("Tourist_Agency_MVC.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId");

                    b.Navigation("Activity");

                    b.Navigation("Agency");
                });
#pragma warning restore 612, 618
        }
    }
}
